version: '3.6'

services:

  # Backend API
  task-manager-api:
    container_name: backend
    # image: node:10.16.0
    build: ./
    command: npm start
    working_dir: /usr/src/task-manager
    environment:
      REDIS_HOST: redis
      MONGODB_URL: mongodb://mongodb/task-manager:27017

    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/task-manager

    # Mongo
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

    